
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

local: &local
  <<: *default
  host: db
  username: postgres
  password: password
  port: 5432

development:
  <<: *default
  database: store_development
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: store_test
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: store_production
  username: store
  url: <%= ENV['DATABASE_URL'] %>
