version: '3'

services:
    db:
        image: postgres:16-alpine
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
        ports:
            - '5432:5432'
        volumes:
            - postgres13:/var/lib/postgresql/data
    redis:
        image: redis:7.0.15-alpine
        ports:
        - '6379:6379'
        volumes:
        - redis_data:/data  
    web:
        stdin_open: true
        tty: true
        build: .
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        volumes:
            - .:/tech-interview-backend-entry-level-main
        ports:
            - "3000:3000"
        depends_on:
            - db
        environment:
            - DATABASE_URL= postgresql://postgres:password@db:5432/store_development
            - DATABASE_HOST=db
            - DATABASE_USERNAME=postgres
            - DATABASE_PASSWORD=password
            - REDIS_URL=redis://redis:6379
    test:
        build: .
        command: bundle exec rspec
        volumes:
            - .:/rails
        depends_on:
            - db
            - redis 
        environment:
            - DATABASE_URL= postgresql://postgres:password@db:5432/store_test
            - REDIS_URL= redis://redis:6379/0
volumes:
    postgres13:
    redis_data: